services:
  - type: worker
    name: 2ndstreet-scraper
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser chromium-chromedriver
      pip install -r requirements.txt
    startCommand: |
      export CHROME_BIN=$(which chromium-browser || which chromium || which google-chrome)
      echo "✅ Using CHROME_BIN=$CHROME_BIN"
      python scraper_line.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
