services:
  - type: cron
    name: 2ndstreet-scraper
    env: python
    schedule: "*/15 * * * *"
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg unzip curl
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable
      pip install -r requirements.txt
    startCommand: |
      export CHROME_BIN=$(which google-chrome-stable)
      echo "✅ Chrome binary path: $CHROME_BIN"
      python scraper_line.py
